services:
  backend:
    build:
      context: ./server
    ports:
      - "8080:8080"
    env_file: ./server/.env
    depends_on:
      - redis
    restart: always
    deploy:
      resources:
        limits:
          memory: 6g
          cpus: "3.5"
